import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Layout from '@/components/Layout/Layout';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Hyper Hire',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins mx-auto antialiased min-h-svh`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
